contact_links:
  - name: For questions about the library
    about: Support questions are better answered in our Slack group.
    url: https://join.slack.com/t/betterproto/shared_invite/zt-f0n0uolx-iN8gBNrkPxtKHTLpG3o1OQ
