name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check-formatting:
    name: Check code/doc formatting
    name: Check code/doc quailty
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Black
      uses: lgeiger/black-action@master
      with:
        args: --check src/ tests/

    - name: Install rST dependcies
      run: python -m pip install doc8
    - name: Lint documentation for errors
      run: python -m doc8 docs --max-line-length 88 --ignore-path-errors "docs/migrating.rst;D001"
      # it has a table which is longer than 88 characters long
